name: Create MLIR conda env

on:
    workflow_call:

jobs:
    create_mlir_env:
        runs-on:
            - self-hosted
            - glados
        steps:
            - name: Checkout torch-mlir repo
              uses: actions/checkout@v3
              with:
                repository: 'https://github.com/intel-ai/torch-mlir'
                ref: 'cpu-proto'
                submodules: recursive
            - name: Create conda env to build MLIR
              run: |
                tests/scripts/create-mlir-env.sh torch-mlir
            - name: Build torch-mlir
              run: |
                tests/scripts/build-mlir.sh torch-mlir
