name: Run mlp test on requested platforms

on:
    workflow_call:
        inputs:
            conda_env:
                required: true
                type: string
                description: Name of conda env
            jit:
                required: true
                type: string
                description: Type of JIT to use
            engine:
                required: true
                type: string
                description: Type of engine to use

jobs:
    mlp_test:
        runs-on:
            - self-hosted
            - glados
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/initial_setup
              with:
                  conda_env: ${{ inputs.conda_env }}
            - name: Run MLP test
              shell: bash -el {0}
              run: |
                  env
                  python tests/launcher.py -m MLP -j ${{ inputs.jit }} -e ${{ inputs.engine }}
